version: '3'
services:
  api:
    env_file:
      - "app/.env"
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/aws/api:v0.1
    ports:
      - "1240:8040"
    restart: always
    volumes:
      - /var/log:/aws/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - net_poptape
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "1241:5432"
    volumes:
      - poptape_awsdata:/var/lib/postgresql/data
    networks:
      - net_poptape
networks:
  net_poptape:
    external: true
volumes:
  poptape_awsdata:  
